language: ruby
rvm:
  - "2.3.3"
  - "2.2.6"
  - 2.1
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - gemfile: gemfiles/rails_5.gemfile
      rvm: 2.1

script: bundle exec rspec

